"""initial migration

Revision ID: fb0c6f76da1a
Revises: 
Create Date: 2025-04-11 18:22:00.410030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb0c6f76da1a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 移除修改列类型的操作，因为SQLite不支持ALTER COLUMN
    # op.alter_column('website', 'visible_to',
    #           existing_type=sa.TEXT(),
    #           type_=sa.String(length=512),
    #           existing_nullable=True,
    #           existing_server_default=sa.text('("")'))
    
    # 直接将当前数据库状态标记为已迁移
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 同样，移除修改列类型的操作
    # op.alter_column('website', 'visible_to',
    #           existing_type=sa.String(length=512),
    #           type_=sa.TEXT(),
    #           existing_nullable=True,
    #           existing_server_default=sa.text('("")'))
    pass
    # ### end Alembic commands ###
